name: Display Environment Name

on:
    workflow_dispatch:

jobs:
    Display_Environment_with_Conditions:
        name: test environmental variables
        runs-on: ubuntu-latest
        environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Lab' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Display Variable for Lab
              if: vars.ENVIRONMENTNAME == 'bchealth-cloud-azure-alz-lab'
              run: 
                echo ${{ vars.ENVIRONMENTNAME }}
                echo join(${{ vars.ENVIRONMENTNAME }},'-network-bchealth')

            - name: Display Variable for Prod
              if: vars.ENVIRONMENTNAME == 'bchealth-cloud-azure-alz-main'
              run: 
                echo ${{ vars.ENVIRONMENTNAME }}
                echo join(${{ vars.ENVIRONMENTNAME }},'-network-bchealth')

