name: Display Environment Name

on:
    workflow_dispatch:

jobs:
    Display_Environment_with_Conditions:
        name: test environmental variables test2
        runs-on: ubuntu-latest
        environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Lab' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Display Variable
              run: 
                echo ${{ vars.ENVIRONMENTNAME }}

