# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

name: 4-00 - Policy Root

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
    working-directory: scripts/deployments

jobs:

  Custom_Policy_Definitions:
    name: Custom policy definitions
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Lab' }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy policy definitions in Lab Environment
      if: github.event.inputs.environmentName == 'bchealth-cloud-azure-alz-lab'
      run: |
        ./RunWorkflows.ps1 `
          -DeployCustomPolicyDefinitions `
          -EnvironmentName '${{env.ENVIRONMENTNAME}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_SPN_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF}

    - name: Deploy policy definitions in Prod Environment
      if: github.event.inputs.environmentName == 'bchealth-cloud-azure-alz-main'
      run: |
        ./RunWorkflows.ps1 `
          -DeployCustomPolicyDefinitions `
          -EnvironmentName '${{env.ENVIRONMENTNAME}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_SPN_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF}

  Custom_Policy_Set_Definitions_Lab:
    if: github.event.inputs.environmentName == 'bchealth-cloud-azure-alz-lab'
    name: Define custom Policysets_Lab
    needs: Custom_Policy_Definitions

    strategy:
      matrix:
        policySetDefinitionName:
          - LogAnalytics
          - Network
          - Tags
      fail-fast: false

    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Lab' }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy policy set definition in Lab Environment
      run: |
        ./RunWorkflows.ps1 `
          -DeployCustomPolicySetDefinitions `
          -CustomPolicySetDefinitionNames '${{ matrix.policySetDefinitionName }}' `
          -EnvironmentName '${{env.ENVIRONMENTNAME}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_SPN_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF}

  Custom_Policy_Set_Definitions_Prod:
    if: github.event.inputs.environmentName == 'bchealth-cloud-azure-alz-main'
    name: Define custom Policysets_Prod
    needs: Custom_Policy_Definitions

    strategy:
      matrix:
        policySetDefinitionName:
          - LogAnalytics
          - Network
          - Tags
      fail-fast: false

    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Lab' }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy policy set definition in Prod Environment
      run: |
        ./RunWorkflows.ps1 `
          -DeployCustomPolicySetDefinitions `
          -CustomPolicySetDefinitionNames '${{ matrix.policySetDefinitionName }}' `
          -EnvironmentName '${{env.ENVIRONMENTNAME}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_SPN_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF}

  Custom_Policy_Set_Assignments_Lab:
    name: Assign custom policyset_Lab
    if: github.event.inputs.environmentName == 'bchealth-cloud-azure-alz-lab'
    needs:
      - Custom_Policy_Definitions
      - Custom_Policy_Set_Definitions_Lab

    strategy:
      matrix:
        policySetAssignmentName:
          - lab-network-root-audit
          - lab-tags-root-audit
      fail-fast: false

    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Lab' }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy policy set assignment in Lab Environment
      run: |
        ./RunWorkflows.ps1 `
          -DeployCustomPolicySetAssignments `
          -CustomPolicySetAssignmentNames '${{ matrix.policySetAssignmentName }}' `
          -EnvironmentName '${{env.ENVIRONMENTNAME}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_SPN_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF} `
          -CustomPolicySetAssignmentManagementGroupId '1c0dd63b-ccb3-4433-a6e0-f9a0a2890e14'

  Custom_Policy_Set_Assignments_Prod:
    name: Assign custom policyset_Prod
    if: github.event.inputs.environmentName == 'bchealth-cloud-azure-alz-main'
    needs:
      - Custom_Policy_Definitions
      - Custom_Policy_Set_Definitions_Prod

    strategy:
      matrix:
        policySetAssignmentName:
          - prod-network-root-audit
          - prod-tags-root-audit
      fail-fast: false

    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Lab' }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy policy set assignment in Prod Environment
      run: |
        ./RunWorkflows.ps1 `
          -DeployCustomPolicySetAssignments `
          -CustomPolicySetAssignmentNames '${{ matrix.policySetAssignmentName }}' `
          -EnvironmentName '${{env.ENVIRONMENTNAME}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_SPN_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF} `
          -CustomPolicySetAssignmentManagementGroupId '31f660a5-192a-4db3-92ba-ca424f1b259e'

  Builtin_Policy_Set_Assignments_Lab:
    name: Assign built-in policyset in Lab Environment
    if: github.event.inputs.environmentName == 'bchealth-cloud-azure-alz-lab'

    strategy:
      matrix:
        policySetAssignmentName:
          - lab-asb-root-audit
          - lab-pbmm-root-audit
          - lab-cis-msft-130-root-audit
          - lab-location-root-audit
          - lab-nist80053r5-root-audit
      fail-fast: false

    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Lab' }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy policy set assignment in Lab Environment
      run: |
        ./RunWorkflows.ps1 `
          -DeployBuiltinPolicySetAssignments `
          -BuiltinPolicySetAssignmentNames '${{ matrix.policySetAssignmentName }}' `
          -EnvironmentName '${{env.ENVIRONMENTNAME}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_SPN_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF} `
          -BuiltinPolicySetAssignmentManagementGroupId '1c0dd63b-ccb3-4433-a6e0-f9a0a2890e14'

  Builtin_Policy_Set_Assignments_Prod:
    name: Assign built-in policyset in Prod Environment
    if: github.event.inputs.environmentName == 'bchealth-cloud-azure-alz-main'

    strategy:
      matrix:
        policySetAssignmentName:
          - prod-asb-root-audit
          - prod-pbmm-root-audit
          - prod-cis-msft-130-root-audit
          - prod-location-root-audit
          - prod-nist80053r5-root-audit
      fail-fast: false

    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Lab' }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy policy set assignment in Prod Environment
      run: |
        ./RunWorkflows.ps1 `
          -DeployBuiltinPolicySetAssignments `
          -BuiltinPolicySetAssignmentNames '${{ matrix.policySetAssignmentName }}' `
          -EnvironmentName '${{env.ENVIRONMENTNAME}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_SPN_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF} `
          -BuiltinPolicySetAssignmentManagementGroupId '31f660a5-192a-4db3-92ba-ca424f1b259e'